-- supabase/setup_ticket_comments.sql
-- Run this in Supabase SQL Editor to enable ticket comments (updates via comments).
-- Assumes you already have:
--   tickets (id bigint/serial primary key)
--   ticket_photos (ticket_id FK -> tickets.id)

create table if not exists public.ticket_comments (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  author text,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists ticket_comments_ticket_id_idx
  on public.ticket_comments(ticket_id);

